INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Barista', 1800)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Barman', 1800)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Kelner', 1400)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Kierowca', 1400)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Kierownik', 3500)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Księgowy', 1900)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Kucharz', 1800)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Manager', 3000)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Opiekun sali', 1800)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Pomoc kuchenna', 1300)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Sommelier', 1800)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Szef kuchni', 2000)
INSERT INTO [dbo].[Positions] ([Name], [Starting_salary]) VALUES (N'Zwolniony', 0)
