SET IDENTITY_INSERT [dbo].[Tables] ON
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (1, 4)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (2, 4)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (3, 4)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (4, 4)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (5, 4)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (6, 4)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (7, 4)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (8, 2)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (9, 2)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (10, 2)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (11, 2)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (12, 2)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (13, 2)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (14, 2)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (15, 6)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (16, 6)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (17, 6)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (18, 6)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (19, 6)
INSERT INTO [dbo].[Tables] ([NUMBER], [Number_of_seats]) VALUES (20, 8)
SET IDENTITY_INSERT [dbo].[Tables] OFF
