INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Przystawki zimne')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Przystawki ciepłe')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Zupy')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Sałatki')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Drób')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Dziczyzna')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Ryby')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Wieprzowina')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Wołowina')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Desery')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Napoje alkoholowe')
INSERT INTO [dbo].[Types] ([Name]) VALUES (N'Napoje ciepłe')
