INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Barista')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Barman')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Kelner')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Kierowca')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Kucharz')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Opiekun sali')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Pomoc kuchenna')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Sommelier')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Szef kuchni')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Kierownik')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_LOG_IN', N'Księgowy')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_DELIVERIES', N'Kierownik')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_DELIVERIES', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_DELIVERIES', N'Księgowy')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_DELIVERIES', N'Szef kuchni')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_RESERVATIONS', N'Kierownik')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_RESERVATIONS', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_RESERVATIONS', N'Barista')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_RESERVATIONS', N'Barman')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_RESERVATIONS', N'Kelner')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_EMPLOYEES', N'Kierownik')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_EMPLOYEES', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_EMPLOYEES', N'Księgowy')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Barista')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Barman')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Kelner')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Kierowca')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Kucharz')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Opiekun sali')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Pomoc kuchenna')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Sommelier')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Szef kuchni')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Kierownik')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_MENU', N'Księgowy')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Barista')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Barman')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Kelner')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Kierowca')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Kucharz')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Opiekun sali')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Pomoc kuchenna')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Sommelier')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Szef kuchni')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Kierownik')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_SEE_ORDERS', N'Księgowy')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_DELIVERIES', N'Kierownik')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_DELIVERIES', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_EMPLOYEES', N'Kierownik')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_EMPLOYEES', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_MENU', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_MENU', N'Szef kuchni')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_MENU', N'Kierownik')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_ORDERS', N'Barista')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_ORDERS', N'Barman')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_ORDERS', N'Kelner')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_ORDERS', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_ORDERS', N'Kierownik')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_RESERVATIONS', N'Barista')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_RESERVATIONS', N'Barman')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_RESERVATIONS', N'Kelner')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_RESERVATIONS', N'Manager')
INSERT INTO [dbo].[Having_privileges] ([Privilege_Name], [Position_Name]) VALUES (N'CAN_MODIFY_RESERVATIONS', N'Kierownik')
