//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public System.DateTime DATE { get; set; }
        public System.TimeSpan START { get; set; }
        public System.TimeSpan End { get; set; }
        public string Name { get; set; }
        public int Table_Number { get; set; }
    
        public virtual Table Table { get; set; }
    }
}
